### PR TITLE
Create Crystolline.json

### PR DESCRIPTION
**Pull request by Crystolline**

### CODE REVIEW

**Comment by bleachc** [comment]
Please check your JSON, it doesn't appear to be valid. https://jsonlint.com/

**Comment by Crystolline** [comment]
Extra comma in links list, should be fixed now.

**Comment by bleachc** [comment]
Please check your JSON, it doesn't appear to be valid. https://jsonlint.com/

**Comment by bleachc** [comment]
Please check your JSON, it doesn't appear to be valid. https://jsonlint.com/

**Pull request merged**
